import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import * as Material from "@angular/material";
import * as Bootstrap from "@ng-bootstrap/ng-bootstrap";
import { NgxSpinnerModule } from 'ngx-spinner';
import { NgxMatSelectSearchModule } from 'ngx-mat-select-search';
import { MatFormFieldModule, MatInputModule } from "@angular/material";

@NgModule({
	declarations: [],
	imports: [
		MatFormFieldModule,
        MatInputModule,
		CommonModule,
		Material.MatButtonModule,
		Material.MatMenuModule,
		Material.MatSelectModule,
		Material.MatInputModule,
		Material.MatTableModule,
		Material.MatAutocompleteModule,
		Material.MatRadioModule,
		Material.MatIconModule,
		Material.MatNativeDateModule,
		Material.MatProgressBarModule,
		Material.MatDatepickerModule,
		Material.MatCardModule,
		Material.MatPaginatorModule,
		Material.MatSortModule,
		Material.MatCheckboxModule,
		Material.MatProgressSpinnerModule,
		Material.MatSnackBarModule,
		Material.MatTabsModule,
		Material.MatTooltipModule,
		Material.MatDialogModule,
		Material.MatFormFieldModule,
		Material.MatDividerModule,
		Bootstrap.NgbDropdownModule,
		Bootstrap.NgbTabsetModule,
		Bootstrap.NgbTooltipModule,
		Bootstrap.NgbModule,
		Material.MatSlideToggleModule,
		NgxSpinnerModule,
		NgxMatSelectSearchModule,
	],
	exports: [
		Material.MatButtonModule,
		Material.MatMenuModule,
		Material.MatSelectModule,
		Material.MatInputModule,
		Material.MatTableModule,
		Material.MatAutocompleteModule,
		Material.MatRadioModule,
		Material.MatIconModule,
		Material.MatNativeDateModule,
		Material.MatProgressBarModule,
		Material.MatDatepickerModule,
		Material.MatCardModule,
		Material.MatPaginatorModule,
		Material.MatSortModule,
		Material.MatCheckboxModule,
		Material.MatProgressSpinnerModule,
		Material.MatSnackBarModule,
		Material.MatTabsModule,
		Material.MatTooltipModule,
		Material.MatDialogModule,
		Material.MatFormFieldModule,
		Material.MatDividerModule,
		Material.MatExpansionModule,
		Bootstrap.NgbDropdownModule,
		Bootstrap.NgbTabsetModule,
		Bootstrap.NgbTooltipModule,
		Bootstrap.NgbModule,
		Material.MatSlideToggleModule,
		NgxSpinnerModule,
		NgxMatSelectSearchModule,
		
	],
})
export class MaterialsModule {}
